apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-node-deployment
    labels:
        app: my-node-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-node
    template:
        metadata:
            labels:
                app: my-node
        spec:
            containers:
            - name: my-node-app
              image: sharmilas22/my-node:latest
              ports:
                - containerPort: 3000

